### ISSUE TITLE
require() of ES Module globby

### ISSUE THREAD

**Issue by minkoonim** [eslint-stylistic/eslint-stylistic#27]
all of a sudden,
without updating any package,
it happened.

eslint.config.js
```
import antfu from '@antfu/eslint-config'

export default antfu()
```

error message:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/minkoonim/admin/node_modules/globby/index.js from /home/minkoonim/admin/node_modules/@typescript-eslint/typescript-estree/dist/parseSettings/resolveProjectList.js not supported.
Instead change the require of index.js in /home/minkoonim/admin/node_modules/@typescript-eslint/typescript-estree/dist/parseSettings/resolveProjectList.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@typescript-eslint/typescript-estree/dist/parseSettings/resolveProjectList.js:8:18)
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@typescript-eslint/typescript-estree/dist/parseSettings/createParseSettings.js:14:30)
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@typescript-eslint/typescript-estree/dist/parser.js:17:31)
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@typescript-eslint/typescript-estree/dist/index.js:18:16)
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@typescript-eslint/type-utils/dist/TypeOrValueSpecifier.js:30:29)
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@typescript-eslint/type-utils/dist/isTypeReadonly.js:32:32)
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@typescript-eslint/type-utils/dist/index.js:26:14)
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@stylistic/eslint-plugin-ts/dist/block-spacing.js:6:1)
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@stylistic/eslint-plugin-ts/dist/index.js:3:20)
    at Object.<anonymous> (/home/minkoonim/admin/node_modules/@stylistic/eslint-plugin/dist/index.js:5:10)
```

**Comment by minkoonim** [comment]
closing since reinstalling all the packages did the magic
