### ISSUE TITLE
`@stylistic/eslint-plugin`: inaccurate type declaration exports

### ISSUE THREAD

**Issue by JstnMcBrd** [eslint-stylistic/eslint-stylistic#437]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

# What

This is something I've noticed for a while but haven't brought up until now.

If you examine the transpiled distribution files for this package, you'll notice that the type declaration file and the actual JavaScript file are not in agreement.

```ts
// ./node_modules/@stylistic/eslint-plugin/dist/dts/index.d.ts
...

export { type Rules, type StylisticCustomizeOptions, UnprefixedRuleOptions, configs, customize, plugin as default };
```

```js
// ./node_modules/@stylistic/eslint-plugin/dist/index.js
...

var index = Object.assign(configs.plugin, { configs: configs.configs });
module.exports = index;
```

The type declaration file has some extra type exports, and that's okay - those shouldn't hurt anything (although for some reason, `UnprefixedRuleOptions` isn't marked as `type`, which is weird).

 But the problem is, the export contains a couple additional non-type exports that do not actually exist in the transpiled JavaScript!

Anyone using type-hints from TypeScript could be tricked into thinking they can import the `configs` or `customize` directly from the package like this:

```ts
import { customize } from "@stylistic/eslint-plugin";
export default [
   customize()
];
```
![image](https://github.com/eslint-stylistic/eslint-stylistic/assets/28303477/902f0928-5280-43f8-99b9-ecc1c185d179)

TypeScript is perfectly happy with this! But when you run the code, it crashes spectacularly.

```
Oops! Something went wrong! :(

ESLint: 8.57.0

file:///...
import { customize } from '@stylistic/eslint-plugin';
         ^^^^^^^^^
SyntaxError: Named export 'customize' not found. The requested module '@stylistic/eslint-plugin' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@stylistic/eslint-plugin';
const { customize } = pkg;


    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadFlatConfigFile (...\node_modules\eslint\lib\eslint\flat-eslint.js:303:21)
    at async calculateConfigArray (...\node_modules\eslint\lib\eslint\flat-eslint.js:382:28)
    at async FlatESLint.lintFiles (...\node_modules\eslint\lib\eslint\flat-eslint.js:745:25)
    at async Object.execute (...\node_modules\eslint\lib\cli.js:421:23)
    at async main (...\node_modules\eslint\bin\eslint.js:152:22)
```

Maybe this doesn't seem like a big problem for most users, because `eslint.config.js` is a JavaScript file, so there's no expectation of type-safety to begin with. Nobody will stop you from importing things that don't exist.

But the same thing happens for users who import the package in a TypeScript environment (like writing their own eslint-config, like I do). Those users rightfully expect that TypeScript will ensure type-safety. But the inaccurate types can betray them! This is a violation of the fundamental tenants of TypeScript 😱 

# Why

There's probably a way to change the type declaration file in `packages/eslint-plugin/dts/index.d.ts` to properly reflect what is actually being exported.

But honestly, perhaps the true root of the problem is having separately-defined type declaration files in the first place. I've contributed to this project a few times now, and every time has been fixing a type issue with the declaration files.

There are other issues I haven't mentioned yet:
- The default import has no type hints
- TypeScript sometimes ignores some types in favor of others (which is why #418 didn't work)

So I've gotta ask: why are there separate type declaration files? The `.ts` files contain their own types and can generate their own `.d.ts` files automatically during build, and those are guaranteed to be accurate. Why not just use TypeScript's built-in declaration generation instead of trying to define types manually?

I'm sure there's a reason why the project was set up like this, and I'm genuinely curious to know. As an outsider, I don't want to assume I know better and demand to change the entire build process.

Still, I think getting rid of all of the redundant declaration files and letting TypeScript handle it would fix a lot of issues. Am I missing something? Let me know what you think.

### Reproduction

https://stackblitz.com/edit/github-lkv2nh

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by rgant** [comment]
This is still a problem in 2025 using `@stylistic/eslint-plugin@4.2.0`

```
warning  Caution: `stylistic` also has a named export `configs`. Check if you meant to write `import {configs} from '@stylistic/eslint-plugin'` instead  import-x/no-named-as-default-member
```

But `configs` is undefined at runtime:

```ts
import { configs } from '@stylistic/eslint-plugin';

console.log('@stylistic/eslint-plugin#configs', configs); // undefined
```

Because [`index.ts`](https://github.com/eslint-stylistic/eslint-stylistic/blob/85eeaa16f102190f04801a8bfa9675f6638b51a4/packages/eslint-plugin/src/index.ts#L8) doesn't actually export `configs`

**Comment by 9romise** [comment]
I've checked the latest version, and the issue appears to have been resolved. I'm going to close this issue now.
