### ISSUE TITLE
`key-spacing`: 2.10 introduced crash

### ISSUE THREAD

**Issue by Lippiece** [eslint-stylistic/eslint-stylistic#592]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Thanks for your work.

After upgrading to 2.10, eslint crashes with this rule enabled. Reverting to 2.9 fixes the issue.

I suspect by the changelog this is related to 789d8935de1f05c6f525017bbb55b2729cff55b2 or other spacing changes, but I couldn't figure it out.

```
import stylistic from "@stylistic/eslint-plugin-ts"
```
```
    plugins: {
      "@stylistic/ts"     : stylistic,
    }
```
```
    rules: {
      "@stylistic/ts/key-spacing": [
        1,
        {
          align: "colon",
        },
      ],
    }
```

<details><summary>Stack</summary>
<p>

ESLint: 9.13.0

TypeError: Cannot read properties of undefined (reading 'range')
Occurred while linting /home/lippiece/eslint.config.mjs:1
Rule: "@stylistic/ts/key-spacing"
    at SourceCode.getTokenBefore (/home/lippiece/node_modules/eslint/lib/languages/js/source-code/token-store/index.js:298:18)
    at isSingleLineImportAttributes (/home/lippiece/node_modules/@stylistic/eslint-plugin-ts/dist/rules/key-spacing.js:19:35)
    at verifyImportAttributes (/home/lippiece/node_modules/@stylistic/eslint-plugin-ts/dist/rules/key-spacing.js:447:11)
    at ImportDeclaration (/home/lippiece/node_modules/@stylistic/eslint-plugin-ts/dist/rules/key-spacing.js:461:11)
    at ruleErrorHandler (/home/lippiece/node_modules/eslint/lib/linter/linter.js:1084:48)
    at /home/lippiece/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/lippiece/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/lippiece/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/lippiece/node_modules/eslint/lib/linter/node-event-generator.js:326:22)

</p>
</details> 

### Reproduction

https://stackblitz.com/edit/github-ezj6x6?file=eslint.config.js,src%2Findex.ts

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by niekvb** [comment]
Got the same issue here
